name: fleck

channels:
    - astropy

dependencies:
    - python>=3.5
    - numpy
    - astropy
    - Cython
    - pip:
       - matplotlib
       - sphinx-astropy
       - batman-package
       - shapely