name: fleck

channels:
    - astropy

dependencies:
    - python>=3.5
    - pip:
       - numpy
       - matplotlib
       - sphinx-astropy
       - batman-package
       - shapely
       - astropy
       - Cython