name: fleck

channels:
    - astropy

dependencies:
    - python>=3.5
    - pip:
       - astropy
       - Cython
       - matplotlib
       - numpy
       - sphinx-astropy
       - batman-package
       - shapely